name: Test, Build, and Deploy

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  IMAGE_NAME: ${{ secrets.IMAGE_NAME }}


jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16'

      - name: Check Go Version
        run: go version

      - name: Download Dependencies
        run: go mod download

      - name: Go Test
        run: go test -v ./...

  build:
    name: Build Application Image
    needs: test
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup GCloud CLI
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      - name: Configure Docker
        run: |-
          gcloud --quiet auth configure-docker
      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v0.2.1
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER }}
          location: ${{ secrets.GKE_ZONE }}
          credentials: ${{ secrets.GKE_SA_KEY }}

      - name: Build Docker Image
        run: |-
          docker build --tag "gcr.io/$PROJECT_ID/$IMAGE_NAME:$GITHUB_SHA" .
      - name: Push Image
        run: |-
          docker push "gcr.io/$PROJECT_ID/$IMAGE_NAME:$GITHUB_SHA"
      - name: Setup Kustomize
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize
      - name: Deploy
        run: |-
          kubectl create namespace development --dry-run=client -o yaml | kubectl apply -f -
          kubectl config set-context --current --namespace=development
          ./kustomize edit set image gcr.io/PROJECT_ID/IMAGE:TAG=gcr.io/$PROJECT_ID/$IMAGE_NAME:$GITHUB_SHA
          ./kustomize build . | kubectl apply -f -
          kubectl rollout status deployment/url-parser